const fixedSubstitutions = [
  { from: 'may thurner', to: 'May-Thurner' },
  { from: 'cockett', to: 'Cockett' },
  { from: 'texto', to: 'terço' },
  { from: 'reabilitação', to: 'reabitação' },
  { from: 'bosniak', to: 'Bosniak' },
  { from: 'doppler', to: 'Doppler' },
  { from: 'dopler', to: 'Doppler' },
  { from: 'convite', to: 'Covid-19' },
  { from: 'convide', to: 'Covid-19' },
  { from: 'covid', to: 'Covid-19' },
  { from: 'covide', to: 'Covid-19' },
  { from: 'covid-19', to: 'Covid-19' },
  { from: 'covid 19', to: 'Covid-19' },
  { from: 'Covid-19-19', to: 'Covid-19' },
  { from: 'avc', to: 'AVC' },
  { from: 'actinicas', to: 'actínicas' },
  { from: 'c1', to: 'C1' },
  { from: 'c2', to: 'C2' },
  { from: 'c3', to: 'C3' },
  { from: 'c4', to: 'C4' },
  { from: 'c5', to: 'C5' },
  { from: 'c6', to: 'C6' },
  { from: 'c7', to: 'C7' },
  { from: 't1', to: 'T1' },
  { from: 't2', to: 'T2' },
  { from: 't3', to: 'T3' },
  { from: 't4', to: 'T4' },
  { from: 't5', to: 'T5' },
  { from: 't6', to: 'T6' },
  { from: 't7', to: 'T7' },
  { from: 't8', to: 'T8' },
  { from: 't9', to: 'T9' },
  { from: 't10', to: 'T10' },
  { from: 't11', to: 'T11' },
  { from: 't12', to: 'T12' },
  { from: 'l1', to: 'L1' },
  { from: 'l2', to: 'L2' },
  { from: 'l3', to: 'L3' },
  { from: 'l4', to: 'L4' },
  { from: 'l5', to: 'L5' },
  { from: 's1', to: 'S1' },
  { from: 'L1 L2', to: 'L1-L2' },
  { from: 'L2 L3', to: 'L2-L3' },
  { from: 'L3 L4', to: 'L3-L4' },
  { from: 'L4 L5', to: 'L4-L5' },
  { from: 'L5 S1', to: 'L5-S1' },
  { from: 'ipmn', to: 'IPMN' },
  { from: 'C1 C2', to: 'C1-C2' },
  { from: 'C2 C3', to: 'C2-C3' },
  { from: 'C3 C4', to: 'C3-C4' },
  { from: 'C4 C5', to: 'C4-C5' },
  { from: 'C5 C6', to: 'C5-C6' },
  { from: 'C6 C7', to: 'C6-C7' },
  { from: 'lefort', to: 'Lefort' },
  { from: 'tep', to: 'TEP' },
  { from: 'sindrome', to: 'síndrome' },
  { from: 'bronquicas', to: 'brônquicas' },
  { from: 'horta', to: 'aorta' },
  { from: 'leriche', to: 'Leriche' },
  { from: 'endolique', to: 'endoleak' },
  { from: 'infra renal', to: 'infrarrenal' },
  { from: 'supra aorticos', to: 'supra-aórticos' },
  { from: 'aórtico mesentérica', to: 'aórtico-mesentérica' },
  { from: 'a, também,', to: 'há, também,' },
  { from: 'zap', to: 'ápice' },
  { from: 'na estampa grafias', to: 'nas topografias' },
  { from: 'bronquios fontes', to: 'brônquios-fonte' },
  { from: 'ausencia', to: 'ausência' },
  { from: 'virugla', to: ',' },
  { from: 'corretora', to: 'curvatura' },
  { from: 'lâminas aperas e cremosas e integrais', to: 'Lâminas papiráceas e crivosas integras' },
  { from: 'canais eróticos', to: 'Canais ópticos' },
  { from: 'bicicleta', to: 'discreta' },
  { from: 'leriche', to: 'Leriche' },
  { from: 'takayasu', to: 'Takayasu' },
  { from: 'tvp', to: 'TVP' },
  { from: 'duplo j', to: 'duplo J' },
]

export default fixedSubstitutions
